version: "2"
services:
  webapp:
    build: .
    container_name: webapp
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks: 
      - webnet 
      

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: db
    environment:
      MYSQL_DATABASE: flask-sotisdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - my-db:/var/lib/mysql
    networks: 
      - webnet
    
volumes:
  my-db:

networks:
  webnet:
